### ISSUE TITLE
What is the license for the code?

### ISSUE THREAD

**Issue by tensorturtle** [ssaraff98/tegrastats_parser#1]
Hello ssaraff98, thank you for this elegant code.
It has been helpful in my little Jetson project. I appreciate your work very much.

Are you sharing this code with a permissive MIT license or a copyleft license like GPL3?

Thank you 
Jason Sohn

**Comment by ssaraff98** [comment]
Hi Jason,

Thank you so much for your comment. I do hope to improve the code and add more functionality to it soon.
I am sharing this code under the MIT license. Do feel free to use it.

Regards,
Shristi Saraff

**Comment by jccurtis** [comment]
Hi @ssaraff98, do you plan to add the MIT license as a file (i.e. `LICENSE`)? I have forked it [here](https://github.com/lbl-anp/tegrastats_parser) and plan to refactor into a package with entry points for the scripts, JSON output for `fluentbit` and GitHub actions to publish to pypi (eventually). Without a license file (MIT as you say above) in the repo I don't want to publish to pypi. I'll be working on the fork for some projects in our research group.

EDIT: Forgot to mention, great work on this! 😄
